vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|03 Apr 2009 11:56:08 -0000
vti_extenderversion:SR|6.0.2.5516
vti_author:SR|SWNA\\wlwest
vti_modifiedby:SR|SWNA\\wlwest
vti_timecreated:TR|03 Apr 2009 11:56:08 -0000
vti_cacheddtm:TX|03 Apr 2009 11:56:08 -0000
vti_filesize:IR|35502
vti_cachedtitle:SR|William S. Hart - A Short Biography 
vti_cachedbodystyle:SR|<BODY bgcolor="#6E0E0E" background="Logos/ltwood2.jpg" onLoad="MM_preloadImages('../images/nav/zoo_B.gif','../images/nav/zoo_R.gif','../images/nav/fiesta_B.gif','../images/nav/fiesta_R.gif','../images/nav/hall_B.gif','../images/nav/hall_R.gif','../images/nav/man_B.gif','../images/nav/man_R.gif','../images/nav/mbr_B.gif','../images/nav/mbr_R.gif','../images/nav/out_B.gif','../images/nav/out_R.gif','../images/nav/post_B.gif','../images/nav/post_R.gif','../images/nav/pow_B.gif','../images/nav/pow_R.gif','../images/nav/silents_B.gif','../images/nav/silents_R.gif','../images/nav/specials_B.gif','../images/nav/specials_R.gif','../images/nav/film_B.gif','../images/nav/film_R.gif')" style="text-align: right">
vti_cachedlinkinfo:VX|Q|WSH.css S|Logos/ltwood2.jpg S|Logos/WSHheader130.jpg S|logos/FHPMBHeader119.gif S|logos/WHHRMwdEd.gif H|xhome.asp S|Buttons/Home30.gif H|museum.asp S|logos/Museum30.gif H|park.asp S|logos/The\\ Park30.gif H|tours.asp S|logos/Tours30.gif H|events.asp S|logos/Events30.gif H|bio.asp S|logos/Hart\\ Bio.gif H|films.asp S|logos/Hart\\ Films30.gif H|maps.asp S|logos/Maps30.gif H|links.asp S|logos/Links30.gif S|images/WillSHart(hazy).jpg S|images/WilliamHarttiny.jpg S|Logos/WSH\\ Bio1.png H|images/471px-Hartgray.jpg S|images/471px-Hartgray_small.jpg S|images/scrnshotSilentMan.jpg H|http://en.wikipedia.org/wiki/Costumes H|http://en.wikipedia.org/wiki/Theatrical_property S|images/HartHousesepia.jpg S|images/screenshotTumble.jpg H|http://www.hartmuseum.org/ H|xhome.asp S|Buttons/Home30.gif H|museum.asp S|Buttons/Museum30.gif H|parkmap.asp S|Buttons/The\\ Park30.gif H|tours.asp S|Buttons/Tours30.gif H|events.asp S|Buttons/Events30.gif H|bio.asp S|Buttons/Hart\\ Bio.gif H|films.asp S|Buttons/Hart\\ Films30.gif H|maps.asp S|Buttons/Maps30.gif H|links.asp S|Buttons/Links30.gif H|credits.asp S|Buttons/Credits30.gif K|tours.asp S|Buttons/Fees30.gif H|fritz.asp S|Buttons/Fritz30.gif H|films2.asp S|Buttons/Films30.gif H|friends.asp S|Buttons/Friends30.gif H|info.asp S|Buttons/Info30.gif H|photos.asp S|Buttons/Photos30.gif H|tales.asp S|Buttons/Tales30.gif H|more.asp S|Buttons/More30.gif H|http://www.seastwood.com/cyberia_design.asp S|logos/CDwiztemp.jpg H|http://www.seastwood.com/clint/index.asp S|logos/CEGoldBlk128.jpg H|http://www.seastwood.com/index.asp S|logos/SEComBlSm.png
vti_cachedsvcrellinks:VX|FQUS|WSH.css FSUS|Logos/ltwood2.jpg FSUS|Logos/WSHheader130.jpg FSUS|logos/FHPMBHeader119.gif FSUS|logos/WHHRMwdEd.gif FHUS|xhome.asp FSUS|Buttons/Home30.gif FHUS|museum.asp FSUS|logos/Museum30.gif FHUS|park.asp FSUS|logos/The\\ Park30.gif FHUS|tours.asp FSUS|logos/Tours30.gif FHUS|events.asp FSUS|logos/Events30.gif FHUS|bio.asp FSUS|logos/Hart\\ Bio.gif FHUS|films.asp FSUS|logos/Hart\\ Films30.gif FHUS|maps.asp FSUS|logos/Maps30.gif FHUS|links.asp FSUS|logos/Links30.gif FSUS|images/WillSHart(hazy).jpg FSUS|images/WilliamHarttiny.jpg FSUS|Logos/WSH\\ Bio1.png FHUS|images/471px-Hartgray.jpg FSUS|images/471px-Hartgray_small.jpg FSUS|images/scrnshotSilentMan.jpg NHHS|http://en.wikipedia.org/wiki/Costumes NHHS|http://en.wikipedia.org/wiki/Theatrical_property FSUS|images/HartHousesepia.jpg FSUS|images/screenshotTumble.jpg NHHS|http://www.hartmuseum.org/ FHUS|xhome.asp FSUS|Buttons/Home30.gif FHUS|museum.asp FSUS|Buttons/Museum30.gif FHUS|parkmap.asp FSUS|Buttons/The\\ Park30.gif FHUS|tours.asp FSUS|Buttons/Tours30.gif FHUS|events.asp FSUS|Buttons/Events30.gif FHUS|bio.asp FSUS|Buttons/Hart\\ Bio.gif FHUS|films.asp FSUS|Buttons/Hart\\ Films30.gif FHUS|maps.asp FSUS|Buttons/Maps30.gif FHUS|links.asp FSUS|Buttons/Links30.gif FHUS|credits.asp FSUS|Buttons/Credits30.gif FHUS|tours.asp FSUS|Buttons/Fees30.gif FHUS|fritz.asp FSUS|Buttons/Fritz30.gif FHUS|films2.asp FSUS|Buttons/Films30.gif FHUS|friends.asp FSUS|Buttons/Friends30.gif FHUS|info.asp FSUS|Buttons/Info30.gif FHUS|photos.asp FSUS|Buttons/Photos30.gif FHUS|tales.asp FSUS|Buttons/Tales30.gif FHUS|more.asp FSUS|Buttons/More30.gif NHHS|http://www.seastwood.com/cyberia_design.asp FSUS|logos/CDwiztemp.jpg NHHS|http://www.seastwood.com/clint/index.asp FSUS|logos/CEGoldBlk128.jpg NHHS|http://www.seastwood.com/index.asp FSUS|logos/SEComBlSm.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 keywords Sheila\\ Miller,movies,films,actor,director,producer,writer,cowboy,western,star,classic,silent,park,museum,fritz,william,S.,Hart,friends,ranch,mansion,animals,western\\ art,artwork, description The\\ Friends\\ of\\ Hart\\ Park\\ and\\ Museum\\ -\\ Screen\\ Legend\\ William\\ S.\\ Hart\\ had\\ a\\ long\\ and\\ sucessful\\ Hollywood\\ film\\ career.\\ He\\ donated\\ his\\ 260\\ acre\\ ranch\\ and\\ retirement\\ mansion\\ to\\ the\\ people\\ of\\ Los\\ Angeles,\\ it's\\ now\\ known\\ as\\ "Hart\\ Park\\ and\\ Museum".\\  GENERATOR IBM\\ WebSphere\\ Studio HTTP-EQUIV=Content-Style-Type text/css
vti_charset:SR|iso-8859-1
vti_generator:SR|IBM WebSphere Studio
vti_title:SR|William S. Hart - A Short Biography 
vti_backlinkinfo:VX|
