vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|03 Apr 2009 11:56:34 -0000
vti_extenderversion:SR|6.0.2.5516
vti_backlinkinfo:VX|animalsranch.asp art.asp bio.asp template29.asp xhome.asp chaplin.asp contact.asp productions.asp events.asp giftshop.asp kids.asp members.asp silents.asp volunteer.asp advertisers.asp cowboy.asp films.asp hall.asp links.asp photos.asp projects.asp powwow-old.asp park.asp Kids_Only/Games/games.html friends.asp tips.asp
vti_author:SR|SWNA\\wlwest
vti_modifiedby:SR|SWNA\\wlwest
vti_timecreated:TR|03 Apr 2009 11:56:34 -0000
vti_cacheddtm:TX|03 Apr 2009 11:56:34 -0000
vti_filesize:IR|36440
vti_cachedtitle:SR|KIDS ONLY - The Friends of Hart Park & Museum 
vti_cachedbodystyle:SR|<BODY bgcolor="#6E0E0E" background="Kids_Only/kidsOnly.gif" onLoad="MM_preloadImages('../images/nav/zoo_B.gif','../images/nav/zoo_R.gif','../images/nav/fiesta_B.gif','../images/nav/fiesta_R.gif','../images/nav/hall_B.gif','../images/nav/hall_R.gif','../images/nav/man_B.gif','../images/nav/man_R.gif','../images/nav/mbr_B.gif','../images/nav/mbr_R.gif','../images/nav/out_B.gif','../images/nav/out_R.gif','../images/nav/post_B.gif','../images/nav/post_R.gif','../images/nav/pow_B.gif','../images/nav/pow_R.gif','../images/nav/silents_B.gif','../images/nav/silents_R.gif','../images/nav/specials_B.gif','../images/nav/specials_R.gif','../images/nav/film_B.gif','../images/nav/film_R.gif')" style="text-align: center">
vti_cachedlinkinfo:VX|Q|WSH.css S|Kids_Only/kidsOnly.gif S|Logos/Kids\\ Only28.gif S|Logos/ant001.gif S|Logos/eyes_057.gif S|Logos/KidsOnlyFlash2.gif S|Logos/WSHheader130.jpg S|logos/FHPMBHeader119.gif S|Logos/WSHPMwood23.gif H|xhome.asp S|Buttons/Home28.gif H|museum.asp S|Buttons/Museum28.gif H|art.asp S|Buttons/The\\ Art28.gif H|park.asp S|Buttons/The\\ Park28.gif H|giftshop.asp S|Buttons/GIFTSHOP28.gif H|hall.asp S|Buttons/HartHall28.gif H|events.asp S|Buttons/Events28.gif H|powwow.asp S|Buttons/PowWCaps28.gif H|silents.asp S|Buttons/Silents28.gif H|cowboy.asp S|Buttons/Shows28.gif H|volunteer.asp S|Buttons/HELP!28.gif H|kids.asp S|Buttons/FORKIDS28.gif H|friends.asp S|Buttons/Friends28.gif H|join.asp S|Buttons/JOIN28.gif H|members.asp S|Buttons/Members28.gif H|cowboy.asp S|Buttons/ActivCap28s.gif H|bio.asp S|Buttons/Hart\\ Bio28.gif H|films.asp S|Buttons/Hart\\ Films28.gif H|fritz.asp S|Buttons/Animals28.gif H|chaplin.asp S|Buttons/News28.gif H|tours.asp S|Buttons/Tours28.gif H|fritz.asp S|Buttons/Fritz28.gif H|contact.asp S|Buttons/CONTACT28.gif H|maps.asp S|Buttons/Maps28.gif H|photos.asp S|Buttons/Photos28.gif H|specials.asp S|Buttons/Specials28.gif H|links.asp S|Buttons/Links28.gif S|Logos/fish_047.gif S|Logos/Kids\\ Only27.gif S|Logos/Sleeping.gif S|http://www.friendsofhartpark.org/Kids_Only/images/kidsOnly_collage.gif H|Kids_Only/Games/games.html S|http://www.friendsofhartpark.org/Kids_Only/images/games_1.gif H|Kids_Only/Pictures/pictures.html S|Kids_Only/images/pictures29.gif H|Kids_Only/Puzzles/puzzles.html S|Kids_Only/images/puzzles29.gif H|Kids_Only/Stories/stories.html S|Kids_Only/images/stories29.gif S|Logos/FriendsoHPM50.gif H|http://www.hartmuseum.org/ H|mailto:dvsews@as.net S|Logos/buttonemail.gif H|http://www.seastwood.com/cyberia_design.asp S|logos/CDwiz28.jpg S|Logos/eyes_015.gif H|http://www.seastwood.com/index.asp S|logos/SEComBlSm.png H|http://www.seastwood.com/clint/index.asp S|http://www.friendsofhartpark.org/logos/CEGoldBlk128.jpg S|Logos/moveingfish.gif S|Logos/eyes_025.gif H|xhome.asp S|Logos/HOME28.gif S|Logos/looking_anim.gif S|Logos/KidsOnlyFlash.gif H|Kids_Only/Games/games.html S|http://www.friendsofhartpark.org/Kids_Only/images/games_1.gif S|Logos/Kids\\ Only3.gif S|Logos/shark_4.gif S|Logos/c2ae2616d55ea4b735c979ae3db4e622.gif S|Logos/KidsOnlyFlash3.gif S|Logos/BigMouse.gif H|kids.asp S|Logos/Kids\\ Only27.gif
vti_cachedsvcrellinks:VX|FQUS|WSH.css FSUS|Kids_Only/kidsOnly.gif FSUS|Logos/Kids\\ Only28.gif FSUS|Logos/ant001.gif FSUS|Logos/eyes_057.gif FSUS|Logos/KidsOnlyFlash2.gif FSUS|Logos/WSHheader130.jpg FSUS|logos/FHPMBHeader119.gif FSUS|Logos/WSHPMwood23.gif FHUS|xhome.asp FSUS|Buttons/Home28.gif FHUS|museum.asp FSUS|Buttons/Museum28.gif FHUS|art.asp FSUS|Buttons/The\\ Art28.gif FHUS|park.asp FSUS|Buttons/The\\ Park28.gif FHUS|giftshop.asp FSUS|Buttons/GIFTSHOP28.gif FHUS|hall.asp FSUS|Buttons/HartHall28.gif FHUS|events.asp FSUS|Buttons/Events28.gif FHUS|powwow.asp FSUS|Buttons/PowWCaps28.gif FHUS|silents.asp FSUS|Buttons/Silents28.gif FHUS|cowboy.asp FSUS|Buttons/Shows28.gif FHUS|volunteer.asp FSUS|Buttons/HELP!28.gif FHUS|kids.asp FSUS|Buttons/FORKIDS28.gif FHUS|friends.asp FSUS|Buttons/Friends28.gif FHUS|join.asp FSUS|Buttons/JOIN28.gif FHUS|members.asp FSUS|Buttons/Members28.gif FHUS|cowboy.asp FSUS|Buttons/ActivCap28s.gif FHUS|bio.asp FSUS|Buttons/Hart\\ Bio28.gif FHUS|films.asp FSUS|Buttons/Hart\\ Films28.gif FHUS|fritz.asp FSUS|Buttons/Animals28.gif FHUS|chaplin.asp FSUS|Buttons/News28.gif FHUS|tours.asp FSUS|Buttons/Tours28.gif FHUS|fritz.asp FSUS|Buttons/Fritz28.gif FHUS|contact.asp FSUS|Buttons/CONTACT28.gif FHUS|maps.asp FSUS|Buttons/Maps28.gif FHUS|photos.asp FSUS|Buttons/Photos28.gif FHUS|specials.asp FSUS|Buttons/Specials28.gif FHUS|links.asp FSUS|Buttons/Links28.gif FSUS|Logos/fish_047.gif FSUS|Logos/Kids\\ Only27.gif FSUS|Logos/Sleeping.gif NSHS|http://www.friendsofhartpark.org/Kids_Only/images/kidsOnly_collage.gif FHUS|Kids_Only/Games/games.html NSHS|http://www.friendsofhartpark.org/Kids_Only/images/games_1.gif FHUS|Kids_Only/Pictures/pictures.html FSUS|Kids_Only/images/pictures29.gif FHUS|Kids_Only/Puzzles/puzzles.html FSUS|Kids_Only/images/puzzles29.gif FHUS|Kids_Only/Stories/stories.html FSUS|Kids_Only/images/stories29.gif FSUS|Logos/FriendsoHPM50.gif NHHS|http://www.hartmuseum.org/ NHUS|mailto:dvsews@as.net FSUS|Logos/buttonemail.gif NHHS|http://www.seastwood.com/cyberia_design.asp FSUS|logos/CDwiz28.jpg FSUS|Logos/eyes_015.gif NHHS|http://www.seastwood.com/index.asp FSUS|logos/SEComBlSm.png NHHS|http://www.seastwood.com/clint/index.asp NSHS|http://www.friendsofhartpark.org/logos/CEGoldBlk128.jpg FSUS|Logos/moveingfish.gif FSUS|Logos/eyes_025.gif FHUS|xhome.asp FSUS|Logos/HOME28.gif FSUS|Logos/looking_anim.gif FSUS|Logos/KidsOnlyFlash.gif FHUS|Kids_Only/Games/games.html NSHS|http://www.friendsofhartpark.org/Kids_Only/images/games_1.gif FSUS|Logos/Kids\\ Only3.gif FSUS|Logos/shark_4.gif FSUS|Logos/c2ae2616d55ea4b735c979ae3db4e622.gif FSUS|Logos/KidsOnlyFlash3.gif FSUS|Logos/BigMouse.gif FHUS|kids.asp FSUS|Logos/Kids\\ Only27.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 keywords Sheila\\ Miller,movies,films,actor,director,producer,writer,cowboy,western,star,classic,silent,park,museum,fritz,william,S.,Hart,friends,ranch,mansion,animals,western\\ art,artwork, description The\\ Friends\\ of\\ Hart\\ Park\\ and\\ Museum\\ -\\ Thanks\\ to\\ screen\\ legend\\ William\\ S.\\ Hart,\\ his\\ 260\\ acre\\ ranch\\ and\\ retirement\\ mansion\\ are\\ now\\ "Hart\\ Park\\ and\\ Museum".\\  GENERATOR IBM\\ WebSphere\\ Studio HTTP-EQUIV=Content-Style-Type text/css
vti_charset:SR|iso-8859-1
vti_generator:SR|IBM WebSphere Studio
vti_title:SR|KIDS ONLY - The Friends of Hart Park & Museum 
