vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|03 Apr 2009 11:56:41 -0000
vti_extenderversion:SR|6.0.2.5516
vti_backlinkinfo:VX|films2.asp home21.asp parkmap.asp sheila.asp template28.asp cowboy2008.asp credits.asp info.asp more.asp morebuttons.asp photos2.asp templatebuttons.asp template2.asp tempsheila.asp bio2.asp tales.asp
vti_author:SR|SWNA\\wlwest
vti_modifiedby:SR|SWNA\\wlwest
vti_timecreated:TR|03 Apr 2009 11:56:41 -0000
vti_cacheddtm:TX|14 Apr 2009 00:31:12 -0000
vti_filesize:IR|30863
vti_cachedtitle:SR|Friends of Hart Park & Museum - MORE 
vti_cachedbodystyle:SR|<BODY bgcolor="#6E0E0E" background="Logos/ltwood2.jpg" onLoad="MM_preloadImages('../images/nav/zoo_B.gif','../images/nav/zoo_R.gif','../images/nav/fiesta_B.gif','../images/nav/fiesta_R.gif','../images/nav/hall_B.gif','../images/nav/hall_R.gif','../images/nav/man_B.gif','../images/nav/man_R.gif','../images/nav/mbr_B.gif','../images/nav/mbr_R.gif','../images/nav/out_B.gif','../images/nav/out_R.gif','../images/nav/post_B.gif','../images/nav/post_R.gif','../images/nav/pow_B.gif','../images/nav/pow_R.gif','../images/nav/silents_B.gif','../images/nav/silents_R.gif','../images/nav/specials_B.gif','../images/nav/specials_R.gif','../images/nav/film_B.gif','../images/nav/film_R.gif')" style="text-align: right">
vti_cachedlinkinfo:VX|Q|WSH.css S|Logos/ltwood2.jpg S|Logos/WSHheader130.jpg S|logos/FHPMBHeader119.gif S|logos/WHHRMwdEd.gif H|xhome.asp S|Buttons/Home30.gif H|museum.asp S|logos/Museum30.gif H|park.asp S|logos/The\\ Park30.gif H|tours.asp S|logos/Tours30.gif H|events.asp S|logos/Events30.gif H|bio.asp S|logos/Hart\\ Bio.gif H|films.asp S|logos/Hart\\ Films30.gif H|maps.asp S|logos/Maps30.gif H|links.asp S|logos/Links30.gif S|Logos/Page\\ Title2.gif H|http://www.scvhistory.com H|http://www.nhm.org H|http://www.nmai.si.edu/ H|http://www.hart-friends.org/Press_Accounts/combined_text.html H|http://www.cmrussell.org/ H|http://www.nctimes.net/~hihorse/page29.htm H|http://www.mentryville.org/ H|http://www.scvhistory.com/scvhistory/hartmansion-const.htm H|http://www.hartmuseum.org/ H|xhome.asp S|Buttons/Home30.gif H|museum.asp S|Buttons/Museum30.gif H|parkmap.asp S|Buttons/The\\ Park30.gif H|tours.asp S|Buttons/Tours30.gif H|events.asp S|Buttons/Events30.gif H|bio.asp S|Buttons/Hart\\ Bio.gif H|films.asp S|Buttons/Hart\\ Films30.gif H|maps.asp S|Buttons/Maps30.gif H|links.asp S|Buttons/Links30.gif H|credits.asp S|Buttons/Credits30.gif K|tours.asp S|Buttons/Fees30.gif H|fritz.asp S|Buttons/Fritz30.gif H|films2.asp S|Buttons/Films30.gif H|friends.asp S|Buttons/Friends30.gif H|info.asp S|Buttons/Info30.gif H|photos.asp S|Buttons/Photos30.gif H|tales.asp S|Buttons/Tales30.gif H|more.asp S|Buttons/More30.gif H|http://www.seastwood.com/cyberia_design.asp S|logos/CDwiztemp.jpg H|http://www.seastwood.com/clint/index.asp S|logos/CEGoldBlk128.jpg H|http://www.seastwood.com/index.asp S|logos/SEComBlSm.png B|/C:/wlwest/pb/Willam\\ S\\ Hart/Website/_private/more.asp.cnt W|_private/more.asp.cnt
vti_cachedsvcrellinks:VX|FQUS|WSH.css FSUS|Logos/ltwood2.jpg FSUS|Logos/WSHheader130.jpg FSUS|logos/FHPMBHeader119.gif FSUS|logos/WHHRMwdEd.gif FHUS|xhome.asp FSUS|Buttons/Home30.gif FHUS|museum.asp FSUS|logos/Museum30.gif FHUS|park.asp FSUS|logos/The\\ Park30.gif FHUS|tours.asp FSUS|logos/Tours30.gif FHUS|events.asp FSUS|logos/Events30.gif FHUS|bio.asp FSUS|logos/Hart\\ Bio.gif FHUS|films.asp FSUS|logos/Hart\\ Films30.gif FHUS|maps.asp FSUS|logos/Maps30.gif FHUS|links.asp FSUS|logos/Links30.gif FSUS|Logos/Page\\ Title2.gif NHHS|http://www.scvhistory.com NHHS|http://www.nhm.org NHHS|http://www.nmai.si.edu/ NHHS|http://www.hart-friends.org/Press_Accounts/combined_text.html NHHS|http://www.cmrussell.org/ NHHS|http://www.nctimes.net/~hihorse/page29.htm NHHS|http://www.mentryville.org/ NHHS|http://www.scvhistory.com/scvhistory/hartmansion-const.htm NHHS|http://www.hartmuseum.org/ FHUS|xhome.asp FSUS|Buttons/Home30.gif FHUS|museum.asp FSUS|Buttons/Museum30.gif FHUS|parkmap.asp FSUS|Buttons/The\\ Park30.gif FHUS|tours.asp FSUS|Buttons/Tours30.gif FHUS|events.asp FSUS|Buttons/Events30.gif FHUS|bio.asp FSUS|Buttons/Hart\\ Bio.gif FHUS|films.asp FSUS|Buttons/Hart\\ Films30.gif FHUS|maps.asp FSUS|Buttons/Maps30.gif FHUS|links.asp FSUS|Buttons/Links30.gif FHUS|credits.asp FSUS|Buttons/Credits30.gif FHUS|tours.asp FSUS|Buttons/Fees30.gif FHUS|fritz.asp FSUS|Buttons/Fritz30.gif FHUS|films2.asp FSUS|Buttons/Films30.gif FHUS|friends.asp FSUS|Buttons/Friends30.gif FHUS|info.asp FSUS|Buttons/Info30.gif FHUS|photos.asp FSUS|Buttons/Photos30.gif FHUS|tales.asp FSUS|Buttons/Tales30.gif FHUS|more.asp FSUS|Buttons/More30.gif NHHS|http://www.seastwood.com/cyberia_design.asp FSUS|logos/CDwiztemp.jpg NHHS|http://www.seastwood.com/clint/index.asp FSUS|logos/CEGoldBlk128.jpg NHHS|http://www.seastwood.com/index.asp FSUS|logos/SEComBlSm.png FBUS|_private/more.asp.cnt
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_botancillaryfiles:VX|_private/more.asp.cnt
vti_error0:SX|This page contains a FrontPage Hit Counter component that will not function properly until you publish your FrontPage Web to a server.
vti_error:IX|1
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 keywords Sheila\\ Miller,movies,films,actor,director,producer,writer,cowboy,western,star,classic,silent,park,museum,fritz,william,S.,Hart,friends,ranch,mansion,animals,western\\ art,artwork, description The\\ Friends\\ of\\ Hart\\ Park\\ and\\ Museum\\ -\\ Thanks\\ to\\ screen\\ legend\\ William\\ S.\\ Hart,\\ his\\ 260\\ acre\\ ranch\\ and\\ retirement\\ mansion\\ are\\ now\\ "Hart\\ Park\\ and\\ Museum".\\  GENERATOR IBM\\ WebSphere\\ Studio HTTP-EQUIV=Content-Style-Type text/css
vti_charset:SR|iso-8859-1
vti_generator:SR|IBM WebSphere Studio
vti_hasruntimebots:BR|true
vti_title:SR|Friends of Hart Park & Museum - MORE 
