vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Jun 2009 23:11:38 -0000
vti_extenderversion:SR|6.0.2.5516
vti_backlinkinfo:VX|animalsranch.asp art.asp bio.asp sheila.asp template29.asp xhome.asp chaplin.asp contact.asp cowboy2008.asp morebuttons.asp productions.asp events.asp kids.asp members.asp museum.asp search.asp template2.asp tempsheila.asp volunteer.asp advertisers.asp cowboy.asp films.asp fritz.asp photos.asp projects.asp tours.asp park.asp friends.asp join.asp tips.asp templatebuttons.asp giftshop.asp maps.asp silents.asp hall.asp links.asp powwow-old.asp home21.asp specials.asp template28.asp
vti_author:SR|SWNA\\wlwest
vti_modifiedby:SR|SWNA\\wlwest
vti_timecreated:TR|03 Apr 2009 11:56:50 -0000
vti_title:SR|Friends of Hart Park and Museum
vti_nexttolasttimemodified:TR|03 Apr 2009 11:56:50 -0000
vti_cacheddtm:TX|07 Jun 2009 23:11:38 -0000
vti_filesize:IR|11383
vti_cachedtitle:SR|Friends of Hart Park and Museum
vti_cachedbodystyle:SR|<BODY bgcolor="#202019" background="images/202019_back.gif" onLoad="MM_preloadImages('images/nav/bDay_B.gif','images/nav/bDay_R.gif','images/nav/fiesta_B.gif','images/nav/fiesta_R.gif','images/nav/hall_B.gif','images/nav/hall_R.gif','images/nav/man_B.gif','images/nav/man_R.gif','images/nav/mbr_B.gif','images/nav/mbr_R.gif','images/nav/out_B.gif','images/nav/out_R.gif','images/nav/post_B.gif','images/nav/post_R.gif','images/nav/pow_B.gif','images/nav/pow_R.gif','images/nav/silents_B.gif','images/nav/silents_R.gif','../images/nav/film_B.gif','../images/nav/film_R.gif')">
vti_cachedlinkinfo:VX|Q|theme/WSH.css S|images/202019_back.gif S|images/topBar_L.gif S|images/spacer.gif S|images/navBar_L.gif H|Event_Pages/powwow.html S|images/nav/pow_B.gif H|Event_Pages/silents.html S|images/nav/silents_B.gif H|Kids_Only/index.htm S|images/nav/kids_B.gif H|Trading_Post/store.html S|images/nav/post_B.gif H|Hart_Hall/hart_hall.html S|images/nav/hall_B.gif H|Mansion/mansion.html S|images/nav/man_B.gif H|The_Friends/membership.html S|images/nav/mbr_B.gif H|Filmography/filmography.html S|images/nav/film_B.gif H|Zoo/animals.html S|images/nav/zoo_B.gif S|images/navBar_L.gif S|images/midBar_L.gif S|images/spacer.gif S|images/middle_L.gif S|images/spacer.gif S|Event_Pages/2009\\ Pow\\ Wow/Poster_with_background_with_border.JPG S|ADs/theFriends.gif H|http://www.artbeyondcontrol.com/index.html S|ADs/kenLubas_ad.gif S|images/botBar_L.gif H|javascript:location='powwow.html';\\ window.open('../Brands/branding.html','WSH','height=370,width=529,menubar=no,scrollbars=no,resizable=no') S|images/nav/branding_B2.gif S|images/spacer.gif H|sitemap.html S|images/nav/siteMap_B.gif H|Legal/notice.html S|images/nav/legal_B.gif S|images/footBar_L.gif S|images/spacer.gif H|index.htm H|The_Friends/volunteer.html H|The_Friends/fhp_organization.html H|Archives/archive.html H|Newsletters/newsletters.html H|links.html H|Contact/contact.html
vti_cachedsvcrellinks:VX|FQUS|theme/WSH.css FSUS|images/202019_back.gif FSUS|images/topBar_L.gif FSUS|images/spacer.gif FSUS|images/navBar_L.gif FHUS|Event_Pages/powwow.html FSUS|images/nav/pow_B.gif FHUS|Event_Pages/silents.html FSUS|images/nav/silents_B.gif FHUS|Kids_Only/index.htm FSUS|images/nav/kids_B.gif FHUS|Trading_Post/store.html FSUS|images/nav/post_B.gif FHUS|Hart_Hall/hart_hall.html FSUS|images/nav/hall_B.gif FHUS|Mansion/mansion.html FSUS|images/nav/man_B.gif FHUS|The_Friends/membership.html FSUS|images/nav/mbr_B.gif FHUS|Filmography/filmography.html FSUS|images/nav/film_B.gif FHUS|Zoo/animals.html FSUS|images/nav/zoo_B.gif FSUS|images/navBar_L.gif FSUS|images/midBar_L.gif FSUS|images/spacer.gif FSUS|images/middle_L.gif FSUS|images/spacer.gif FSUS|Event_Pages/2009\\ Pow\\ Wow/Poster_with_background_with_border.JPG FSUS|ADs/theFriends.gif NHHS|http://www.artbeyondcontrol.com/index.html FSUS|ADs/kenLubas_ad.gif FSUS|images/botBar_L.gif SHUS|javascript:location='powwow.html';\\ window.open('../Brands/branding.html','WSH','height=370,width=529,menubar=no,scrollbars=no,resizable=no') FSUS|images/nav/branding_B2.gif FSUS|images/spacer.gif FHUS|sitemap.html FSUS|images/nav/siteMap_B.gif FHUS|Legal/notice.html FSUS|images/nav/legal_B.gif FSUS|images/footBar_L.gif FSUS|images/spacer.gif FHUS|index.htm FHUS|The_Friends/volunteer.html FHUS|The_Friends/fhp_organization.html FHUS|Archives/archive.html FHUS|Newsletters/newsletters.html FHUS|links.html FHUS|Contact/contact.html
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=ISO-8859-1 GENERATOR Microsoft\\ FrontPage\\ 6.0 HTTP-EQUIV=Content-Style-Type text/css keywords Native\\ American,\\ American\\ Indian,\\ pow\\ wow\\ calendar,\\ \r\npowwow\\ calendar,\\ powwows\\ ,\\ pow\\ wows\\ ,\\ indians\\ ,\\ dancing,\\ singing,\\ music,\\ crafts,\\ \r\nbeadwork,\\ drums,\\ drummers,\\ arts
vti_charset:SR|iso-8859-1
vti_generator:SR|Microsoft FrontPage 6.0
